name: Unit Tests

on:
  pull_request:
    branches:
      - main

jobs:
  rspec:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby
          bundler-cache: true

      - name: Run RuboCop
        run: bundle exec rubocop

      - name: Run unit tests
        run: bundle exec rspec